<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="MongoDB.Driver" Version="3.5.2" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CQRS.Domain\CQRS.Domain.csproj" />
    <ProjectReference Include="..\CQRS.Infraestructure\CQRS.Infraestructure.csproj" />
  </ItemGroup>

</Project>
